title: Kento Miyazawa
description: Portfolio, CV, and blog in Japanese and English
url: "https://miyaken1201.github.io"
baseurl: ""
locale: ja
timezone: Asia/Tokyo

author:
  name    : "Kento Miyazawa"
  avatar  : "/assets/img/avatars/aile-strike-gundam.jpg"   # プロフィール画像のパス
  bio     : "2nd-year Master's student at Chiba Univ."
  location: "Chiba, Japan"
  links:
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/miyaken1201"
    - label: "Email"
      icon : "fas fa-fw fa-square-envelope"
      url  : "mailto:25wm1211@student.gs.chiba-u.jp"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

google_site_verification: "SAsiKPTe9hAJqpMcCG1xbcRCK50MRmzKAsa20vGkbeo"

markdown: kramdown
permalink: /:categories/:title/
post_pagination: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false
      related: false
      sidebar:
        nav: "nav_ja"

include:
  - _pages
